package io.legado.app.model.analyzeRule

import org.junit.Assert.assertEquals
import org.junit.Assert.assertFalse
import org.junit.Assert.assertNotNull
import org.junit.Assert.assertNull
import org.junit.Assert.assertTrue
import org.junit.Test

/**
 * 样本 = app assets 的 font/number.ttf（6000B，真实 TTF）：
 * name/head/cmap/loca/maxp/glyf 全表齐备，cmap 含 format 4(pid0/pid3 同偏移)与 format 0(pid1)，
 * 数字 '0'..'9' -> glyfId 1..10（已用独立解析器按 Microsoft 规范核对）。
 */
class QueryTTFTest {

    private val font by lazy { java.util.Base64.getDecoder().decode(NUMBER_TTF_B64) }
    private val ttf by lazy { QueryTTF(font) }

    @Test
    fun cmapUnicodeToGlyphId() {
        // 数字 0-9 映射 glyfId 1-10；同偏移子表去重（pid0/pid3 共用 offset 只解析一次）
        for (i in 0..9) {
            assertEquals(i + 1, ttf.getGlyfIdByUnicode('0'.code + i))
        }
        assertEquals(10, ttf.unicodeToGlyphId.size)
        // 未映射字符返回保留索引 0
        assertEquals(0, ttf.getGlyfIdByUnicode('A'.code))
        assertEquals(0, ttf.getGlyfIdByUnicode(0x4E00))
    }

    @Test
    fun glyfRoundTrip() {
        // 简单字形轮廓串 "x,y|x,y|..."，与 glyfId 查询结果一致
        for (i in 0..9) {
            val unicode = '0'.code + i
            val glyf = ttf.getGlyfByUnicode(unicode)
            assertNotNull(glyf)
            assertTrue(glyf!!.matches(Regex("""(-?\d+,-?\d+\|?)+""")))
            assertEquals(glyf, ttf.getGlyfById(i + 1))
            // 轮廓数据反查 Unicode
            assertEquals(unicode, ttf.getUnicodeByGlyf(glyf))
        }
        // 10 个数字轮廓互不相同
        assertEquals(10, ttf.glyphToUnicode.size)
        // 查不到的输入走默认值
        assertNull(ttf.getGlyfByUnicode('A'.code))
        assertEquals(0, ttf.getUnicodeByGlyf("no-such-glyph"))
        assertEquals(0, ttf.getUnicodeByGlyf(null))
    }

    @Test
    fun blankUnicode() {
        intArrayOf(0x0009, 0x0020, 0x00A0, 0x2002, 0x2003, 0x2007, 0x200A, 0x200B, 0x200C, 0x200D, 0x202F, 0x205F)
            .forEach { assertTrue(ttf.isBlankUnicode(it)) }
        assertFalse(ttf.isBlankUnicode('0'.code))
        assertFalse(ttf.isBlankUnicode(0x3000)) // 全角空格刻意不在名单内（对齐原实现）
    }

    companion object {
        /** app/src/main/assets/font/number.ttf 的 base64 */
        private const val NUMBER_TTF_B64: String =
        "AAEAAAAOAIAAAwBgT1MvMph36cQAAADsAAAAYGNtYXAKGRDxAAABTAAAAUJjdnQgDCoaDQAAApAAAAAqZnBnbZSo9FQAAAK8AAAJJWdhc3AAAAAQAAAL5AAA" +
        "AAhnbHlm3hZDVgAAC+wAAAbkaGVhZAFTAfcAABLQAAAANmhoZWEL+ALLAAATCAAAACRobXR4CfkCcQAAEywAAAAabG9jYQhcCh4AABNIAAAAGG1heHABOAm2" +
        "AAATYAAAACBuYW1lB8umWgAAE4AAAANmcG9zdPzKAOcAABboAAAAOHByZXAO+8ifAAAXIAAAAE0ABARcAZAABQAEBZoFMwAAAR8FmgUzAAAD0QBmAgAAAAAA" +
        "AAAAAAAAAADgAALvEAAAAAAAACAAAAAAcHlycwBAADAAOQYA/gAAZgeaAgAgAAGfTwEAAAQ6BbAAAAAgAAIAAAADAAAAAwAAABwAAQAAAAAAPAADAAEAAAAc" +
        "AAQAIAAAAAQABAABAAAAOf//AAAAMP///9EAAQAAAAAAAAEGAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABAgME" +
        "BQYHCAkKAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
        "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
        "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAADFAJoAxQDFAJoAmwWwAAAGGAQ6AAD+YAXF/+sGLQRO/+v+SwBEBREAALAALCBksCBgZiOwAFBYZVktsAEs" +
        "IGQgsMBQsAQmWrALQ1tYISMhG4pYILBQUFghsEBZGyCwOFBYIbA4WVkgsAVFYWSwKFBYIbAFRSCwMFBYIbAwWRsgsMBQWCBmIIqKYSCwClBYYBsgsCBQWCGw" +
        "CmAbILA2UFghsDZgG2BZWVkbsAArWVkjsABQWGVZWS2wAiywByNCsAYjQrAAI0KwAEOwBkNRWLAHQyuyAAEAQ2BCsBZlHFktsAMssABDIEWwCUNjsApDYkQt" +
        "sAQssABDIEUgsAArI7EGBCVgIEWKI2EgZCCwIFBYIbAAG7AwUFiwIBuwQFlZI7AAUFhlWbADJSNhREQtsAUssAFgICCwDUNKsABQWCCwDSNCWbAOQ0qwAFJY" +
        "ILAOI0JZLbAGLLAAQ7ACJUKyAAEAQ2BCsQ0CJUKxDgIlQrABFiMgsAMlUFiwAEOwBCVCioogiiNhsAUqISOwAWEgiiNhsAUqIRuwAEOwAiVCsAIlYbAFKiFZ" +
        "sA1DR7AOQ0dgsIBisAlDY7AKQ2IgsQEAFUMgRoojYTiwAkMgRoojYTi1AgECAQEBQ2BCQ2BCLbAHLACwCCNCtg8PCAIAAQhDQkJDIGBgsAFhsQYCKy2wCCwg" +
        "YLAPYCBDI7ABYEOwAiWwAiVRWCMgPLABYCOwEmUcGyEhWS2wCSywCCuwCCotsAosICBHILAJQ2OwCkNiI2E4IyCKVVggRyCwCUNjsApDYiNhOBshWS2wCywA" +
        "sAEWsAoqsAEVMC2wDCwgNbABYC2wDSwAsABFY7AKQ2KwACuwCUOwCkNhY7AKQ2KwACuwABaxAAAuI7AAR7AARmFgOLEMARUqLbAOLCA8IEewCUNjsApDYrAA" +
        "Q2E4LbAPLC4XPC2wECwgPCBHsAlDY7AKQ2KwAENhsAFDYzgtsBEssQIAFiUgLrAIQ2AgRrAAI0KwAiWwCENgSYqKSSNisAEjQrIQAQEVFCotsBIssAAVILAI" +
        "Q2BGsAAjQrIAAQEVFBMusA4qLbATLLAAFSCwCENgRrAAI0KyAAEBFRQTLrAOKi2wFCyxAAEUE7APKi2wFSywESotsBosLbAdLC2wGyywABawBCWwCENgsAQm" +
        "IC6wCENgSbABKyMgPCAuIzixCQEUKy2wGCyxDAQlQrAAFrAEJbAIQ2CwBCUgLrAIQ2BJILAFI0KwASsgsGBQWCCwQFFYswMgBCAbswMmBBpZQkIjILAIQ2BG" +
        "sAVDsIBiYCCwACsgiophILADQ2BkI7AEQ2FkUFiwA0NhG7AEQ2BZsAMlsIBiYbACJUZhOCMgPCM4GyEgsAhDYC4gPC8hWbEJARQrLbAXLLAMI0KwABM+sQkB" +
        "FCstsBkssAAWsAQlsAhDYLAEJbAIQ2BJsAErZYouIyAgPIo4LrEJARQrLbAcLLAAFrAEJbAIQ2CwBCUgLrAIQ2BJILAFI0KwASsgsGBQWCCwQFFYswMgBCAb" +
        "swMmBBpZQkIjILAIQ2CwDEMgsAhDYIojSSNGYLAFQ7CAYmAgsAArIIqKYSCwA0NgZCOwBENhZFBYsANDYRuwBENgWbADJbCAYmEjILADJiNGYTgbI7AMQ0aw" +
        "AiWwCENgsAxDsAhDYElgILAFQ7CAYmAjILAAKyOwBUNgsAArsAUlYbAFJbCAYrAEJmEgsAQlYGQjsAMlYGRQWCEbIyFZIyCwAyYjRmE4WSMgIDywBSNCIzix" +
        "CQEUK7AFQy6wCSstsBYssAATPrEJARQrLbAeLLAAFiAgsAQmsAIlsAhDYCMgLrAIQ2BJIzw4LrEJARQrLbAfLLAAFiAgsAQmsAIlsAhDYCMgLrAIQ2BJIzw4" +
        "IyAuRrACJUZSWCA8WS6xCQEUKy2wICywABYgILAEJrACJbAIQ2AjIC6wCENgSSM8OCMgLkawAiVGUFggPFkusQkBFCstsCEssAAWICCwBCawAiWwCENgIyAu" +
        "sAhDYEkjPDgjIC5GsAIlRlJYIDxZIyAuRrACJUZQWCA8WS6xCQEUKy2wIiywABYgsAwjQiCwCENgLiAgPC8usQkBFCstsCMssAAWILAMI0IgsAhDYC4gIDwv" +
        "IyAuRrACJUZSWCA8WS6xCQEUKy2wJCywABYgsAwjQiCwCENgLiAgPC8jIC5GsAIlRlBYIDxZLrEJARQrLbAlLLAAFiCwDCNCILAIQ2AuICA8LyMgLkawAiVG" +
        "UlggPFkjIC5GsAIlRlBYIDxZLrEJARQrLbAmLLAAFrADJbAIQ2CwAiWwCENgSbAAVFguIDwjIRuwAiWwCENgsAIlsAhDYEm4EABjsAQlsAMlSWOwBCWwCENg" +
        "sAMlsAhDYEm4EABjYiMuIyAgPIo4IyFZLrEJARQrLbAnLLAAFrADJbAIQ2CwAiWwCENgSbAAVFguIDwjIRuwAiWwCENgsAIlsAhDYEm4EABjsAQlsAMlSWOw" +
        "BCWwCENgsAMlsAhDYEm4EABjYiMuIyAgPIo4IyFZIyAuRrACJUZSWCA8WS6xCQEUKy2wKCywABawAyWwCENgsAIlsAhDYEmwAFRYLiA8IyEbsAIlsAhDYLAC" +
        "JbAIQ2BJuBAAY7AEJbADJUljsAQlsAhDYLADJbAIQ2BJuBAAY2IjLiMgIDyKOCMhWSMgLkawAiVGUFggPFkusQkBFCstsCkssAAWsAMlsAhDYLACJbAIQ2BJ" +
        "sABUWC4gPCMhG7ACJbAIQ2CwAiWwCENgSbgQAGOwBCWwAyVJY7AEJbAIQ2CwAyWwCENgSbgQAGNiIy4jICA8ijgjIVkjIC5GsAIlRlJYIDxZIyAuRrACJUZQ" +
        "WCA8WS6xCQEUKy2wKiywABYgsAhDYLAMQyAusAhDYEkgYLAgYGawgGIjICA8ijgusQkBFCstsCsssAAWILAIQ2CwDEMgLrAIQ2BJIGCwIGBmsIBiIyAgPIo4" +
        "IyAuRrACJUZSWCA8WS6xCQEUKy2wLCywABYgsAhDYLAMQyAusAhDYEkgYLAgYGawgGIjICA8ijgjIC5GsAIlRlBYIDxZLrEJARQrLbAtLLAAFiCwCENgsAxD" +
        "IC6wCENgSSBgsCBgZrCAYiMgIDyKOCMgLkawAiVGUlggPFkjIC5GsAIlRlBYIDxZLrEJARQrLbAuLCstsC8ssC4qsAEVMC0AAAAAAQAB//8ADwACAEQAAAJk" +
        "BVUAAwAHAC6xAQAvPLIHBBPtMrEGBdw8sgMCE+0yALEDAC88sgUEE+0ysgcGFPw8sgECE+0yNxEhESUhESFEAiD+JAGY/mgABVX6q0QEzQAAAgBx/+sEEAXF" +
        "AA0AGwAxQAoZFxIQCwkEAgQHK0uwkFBYQBoAAgIBAQAbAAEBDRYAAwMAAQAbAAAADgAXBLAvKwEUAiMiAjURNBIzMhIVJzQmIyIGFREUFjMyNjUEEPvU0/37" +
        "09T9xYyAf4qNfoCKAgL3/uABIPcBrPUBIv7e9Smdtrad/gOduLeeAAABAMMAAALGBcUABQAkQAYDAgEAAgcrS7CQUFhAEQUEAgETAAEAASsAAAAIABcDsC8r" +
        "JSMRBTUlAsbG/sMCAwAE+gOYNgAAAAABAIUAAAQeBcUAGgBFQAwaGRIQDQwKCAEABQcrS7CQUFhALA4BAgECAQAEAhUAAgEEAQIEKQABAQMBABsAAwMNFgAE" +
        "BAAAABsAAAAIABcGsC8rJSE1AT4BNTQmIyIGFSMnJjYzMhYVFAYHARchBB78eAHJeld2aIGHvgIF+NXD4H+C/pECApcAhwIhlK9ZZYGedgay99irc9ym/lIF" +
        "AAAAAQBz/+sEDwXFACoAZkAWAQApJyMhHx4bGQ8NCgkHBQAqASoJBytLsJBQWEBDCwECARQBBwAdAQYFAxUAAgEAAQIAKQAFBwYHBQYpCAEAAAcFAAcBAB0A" +
        "AQEDAQAbAAMDDRYABgYEAQAbAAQEDgQXCLAvKwEyNjU0JiMiBhUjJyYkMzIWFRQGBx4BFRQGIyIkPwEzFBYzMjY1NCYrATUCQ4Rtd3VylbwDBQECycvma2Bu" +
        "c/3Kuv7lBQK8mXl4in+IogM8g3Zuh41qBqTozcdmqC8ss3/I49u0BmqRlXiJiJkAAAAAAgBIAAAERgWwAAoADwA9QA4MCwoJBwYFBAMCAQAGBytLsJBQWEAi" +
        "DQEABAgBAQACFQUBAAMBAQIAAQAAHQAEBAcWAAICCAIXBLAvKwEzFSMRIxEhNQEzASERJwcDfcnJxP2PAmXQ/Z4BngYTAeqa/rABUG8D8fw6AqsBMgAAAAAB" +
        "AJj/6wQTBbAAHwBYQBAdGxcVExIPDQkHBAMCAQcHK0uwkFBYQDsFAQYCHwACBAYRAQUEAxUABAYFBgQFKQACAAYEAgYBAB0AAQEAAAAbAAAABxYABQUDAQAb" +
        "AAMDDgMXB7AvKxsBIRUhAz4BNzYSFRQCIyImPwEzFBYzMjY1NCYjIgYHr1QC2f3NLy9yScrl6+G59gUCsoltfYqLfHRoGQKHAymv/l0jLQEC/v/g2/72ysQG" +
        "d4OwmYusRkkAAAACAIn/6wQoBcUAGgAnAFtAFhwbAQAjIRsnHCcVEw8NCAYAGgEaCAcrS7CQUFhAOAMBAQAEAQIBCwEEAh4BBQQEFQACBwEEBQIEAQAdAAEB" +
        "AAEAGwYBAAANFgAFBQMBABsAAwMOAxcGsC8rATIWFwcuASMiBh0BPgEzMhYVFAIjIgAZARAAEyIGBxUUFjMyNjU0JgKBVqg3Kjl+VImrPadgvNv10Mr+8AEj" +
        "pl2FI6F1e4WPBcUiGpcZH+qzcT1G/M3g/vUBMwEKAU8BAAFO/UdPQ2W517uWjqgAAAAAAQBhAAAEJwWwAAwALUAIDAsKCQUEAwcrS7CQUFhAGAABAQEUAAEB" +
        "AgAAGwACAgcWAAAACAAXBLAvKwEAAhEVIzUQEhMhNSEEJ/7swsXz5vz8A8YFFf64/gr+yJ+fAUoCEQEbmwAAAAADAGb/6wQaBcUAFwAjAC8ARkAOLiwoJiIg" +
        "HBoWFAoIBgcrS7CQUFhAKw8DAgIFARUABQACAwUCAQAdAAQEAQEAGwABAQ0WAAMDAAEAGwAAAA4AFwawLysBFAYHHgEVFAQjIiQ1NDY3LgE1NDYzMhYDNCYj" +
        "IgYVFBYzMjYDNCYjIgYVFBYzMjYD8oBqfJb++8rW/vGZgnCC9cW675ybcnyioX9ymSmDYWuKjGthgQQ8cq0rK7x7ydzcyXu8LCqtcr/Ky/yad5qad3uUlQMf" +
        "aYiDbm+KigAAAAACAF3/6wP4BcUAGgAnAFtAFhwbAQAjIRsnHCcVEw4MCAYAGgEaCAcrS7CQUFhAOB4BBAUEAQEEGAEAARcBAwAEFQcBBAABAAQBAQAdAAUF" +
        "AgEAGwACAg0WBgEAAAMBABsAAwMOAxcGsC8rJTI2PQEOASMiAjU0EjMyABURFAAjIiYnNx4BEzI2NzU0JiMiBhUUFgH1jq8wj1XS7/672gEI/uDjTaFGHkJ/" +
        "fmeNIJKEa4+EhcS0fEdJAQPm3AEX/u76/kb7/ucgH5YgGwH+Xkmso7G/mZa5AAABAAAAAQAAWBFyvF8PPPUAHwgAAAAAAMTwES4AAAAA2KWmHABE/+sERgXF" +
        "AAAACAACAAAAAAAAAAEAAAds/gwAAASBAEQAOwRGAAEAAAAAAAAAAAAAAAAAAAACAuwARASBAHEAwwCFAHMASACYAIkAYQBmAF0AAAAAACwAcgCWAOYBWAGY" +
        "AfgCZgKaAwYDcgABAAAACwAwAAMAAAAAAAIAUABfADAAAACpCSUAAAAAAAAAGAEmAAEAAAAAAAAAHwAAAAEAAAAAAAEABgAfAAEAAAAAAAIABwAlAAEAAAAA" +
        "AAMAEgAsAAEAAAAAAAQADgA+AAEAAAAAAAUAFQBMAAEAAAAAAAYADgBhAAEAAAAAAAcAIABvAAEAAAAAAAkABgCPAAEAAAAAAAsACgCVAAEAAAAAAAwAEwCf" +
        "AAEAAAAAABIADgCyAAMAAQQJAAAAPgDAAAMAAQQJAAEADAD+AAMAAQQJAAIADgEKAAMAAQQJAAMAJAEYAAMAAQQJAAQAHAE8AAMAAQQJAAUAKgFYAAMAAQQJ" +
        "AAYAHAGCAAMAAQQJAAcAQAGeAAMAAQQJAAkADAHeAAMAAQQJAAsAFAHqAAMAAQQJAAwAJgH+AAMAAQQJABIAHAIkRm9udCBkYXRhIGNvcHlyaWdodCBHb29n" +
        "bGUgMjAxMVJvYm90b1JlZ3VsYXJHb29nbGU6Um9ib3RvOjIwMTFSb2JvdG8gUmVndWxhclZlcnNpb24gMS4wMDAwMDsgMjAxMVJvYm90by1SZWd1bGFyUm9i" +
        "b3RvIGlzIGEgdHJhZGVtYXJrIG9mIEdvb2dsZS5Hb29nbGVHb29nbGUuY29tQ2hyaXN0aWFuIFJvYmVydHNvblJvYm90byBSZWd1bGFyAEYAbwBuAHQAIABk" +
        "AGEAdABhACAAYwBvAHAAeQByAGkAZwBoAHQAIABHAG8AbwBnAGwAZQAgADIAMAAxADEAUgBvAGIAbwB0AG8AUgBlAGcAdQBsAGEAcgBHAG8AbwBnAGwAZQA6" +
        "AFIAbwBiAG8AdABvADoAMgAwADEAMQBSAG8AYgBvAHQAbwAgAFIAZQBnAHUAbABhAHIAVgBlAHIAcwBpAG8AbgAgADEALgAwADAAMAAwADAAOwAgADIAMAAx" +
        "ADEAUgBvAGIAbwB0AG8ALQBSAGUAZwB1AGwAYQByAFIAbwBiAG8AdABvACAAaQBzACAAYQAgAHQAcgBhAGQAZQBtAGEAcgBrACAAbwBmACAARwBvAG8AZwBs" +
        "AGUALgBHAG8AbwBnAGwAZQBHAG8AbwBnAGwAZQAuAGMAbwBtAEMAaAByAGkAcwB0AGkAYQBuACAAUgBvAGIAZQByAHQAcwBvAG4AUgBvAGIAbwB0AG8AIABS" +
        "AGUAZwB1AGwAYQByAAAAAgAAAAAAAPxKAGQAAAAAAAAAAAAAAAAAAAAAAAAACwALAAAAEwAUABUAFgAXABgAGQAaABsAHLkIAAgAYyCwCiNCILAAI3CwEEUg" +
        "ILAoYGYgilVYsApDYyNisAkjQrMFBgMCK7MHDAMCK7MNEgMCKxuxCQpDQlmyCygCRVJCswcMBAIrAAAA"
    }
}
