package io.legado.app.constant

object EventBus {
    const val MEDIA_BUTTON = "mediaButton"
    const val RECREATE = "RECREATE"
    const val UP_BOOKSHELF = "upBookToc"
    const val BOOKSHELF_REFRESH = "bookshelfRefresh"
    const val AUDIO_DS = "audioDs"
    const val BATTERY_CHANGED = "batteryChanged"
    const val TIME_CHANGED = "timeChanged"
    const val AUDIO_SUB_TITLE = "audioSubTitle"
    const val AUDIO_STATE = "audioState"
    const val AUDIO_PROGRESS = "audioProgress"
    const val AUDIO_BUFFER_PROGRESS = "audioBufferProgress"
    const val AUDIO_SIZE = "audioSize"
    const val AUDIO_SPEED = "audioSpeed"
    const val AUDIO_COVER = "audioCover"
    const val AUDIO_LOADING = "audioLoading"
    const val NOTIFY_MAIN = "notifyMain"
    const val WEB_SERVICE = "webService"
    const val UP_DOWNLOAD = "upDownload"
    const val UP_DOWNLOAD_STATE = "upDownloadState"
    const val SAVE_CONTENT = "saveContent"
    const val CHECK_SOURCE = "checkSource"
    const val CHECK_SOURCE_DONE = "checkSourceDone"
    const val SOURCE_CHANGED = "sourceChanged"
    const val SEARCH_RESULT = "searchResult"
    const val READ_ALOUD_PLAY = "readAloudPlay"
    const val EXPORT_BOOK = "exportBook"
    const val UP_MANGA_CONFIG = "upMangaConfig"
    const val PLAY_MODE_CHANGED = "playModeChanged"
    const val UP_EXPLORE_PINNED = "upExplorePinned"
    const val REFRESH_LOGIN_UI = "refreshLoginUi"
    const val REFRESH_EXPLORE = "refreshExplore"
    const val REFRESH_BOOK_INFO = "refreshBookInfo"
    const val STOP_UP_BOOK = "stopUpBook"
    const val HOME_TAB = "homeTab"
    const val HOME_SECTION = "homeSection"
    const val DEFAULT_COVER_CHANGED = "defaultCoverChanged"
    const val SOURCE_UI_REQUEST = "sourceUiRequest"

    /** 主题配置增改后通知刷新主题列表 (对照 app 端 ThemeCustomizeDialog.RESULT_CONFIG_CHANGED) */
    const val THEME_CONFIG_CHANGED = "themeConfigChanged"
}
