package io.legado.app.lib.epublib.domain

import java.io.Serializable
import javax.xml.namespace.QName

/**
 * A Book's collection of Metadata.
 * In the future it should contain all Dublin Core attributes, for now
 * it contains a set of often-used ones.
 * 
 * @author paul
 */
class Metadata : Serializable {
    @get:Suppress("unused")
    var isAutoGeneratedId: Boolean //true;
        private set
    var authors: MutableList<Author?> = ArrayList<Author?>()
    var contributors: MutableList<Author?> = ArrayList<Author?>()
    var dates: MutableList<Date?> = ArrayList<Date?>()
    var language: String? = DEFAULT_LANGUAGE

    /**
     * Metadata properties not hard-coded like the author, title, etc.
     * 
     * @return Metadata properties not hard-coded like the author, title, etc.
     */
    var otherProperties: MutableMap<QName?, String?>? = HashMap<QName?, String?>()
    var rights: MutableList<String?>? = ArrayList<String?>()
    var titles: MutableList<String?>? = ArrayList<String?>()
    private var identifiers: MutableList<Identifier?> = ArrayList<Identifier?>()
    var subjects: MutableList<String?>? = ArrayList<String?>()
    var format: String? = MediaTypes.EPUB.name
    var types: MutableList<String?> = ArrayList<String?>()
    var descriptions: MutableList<String?> = ArrayList<String?>()
    var publishers: MutableList<String?> = ArrayList<String?>()
    private var metaAttributes: MutableMap<String?, String?> = HashMap<String?, String?>()

    init {
        identifiers.add(Identifier())
        this.isAutoGeneratedId = true
    }

    @Suppress("unused")
    fun addDate(date: Date?): Date? {
        this.dates.add(date)
        return date
    }

    fun addAuthor(author: Author?): Author? {
        authors.add(author)
        return author
    }

    fun addContributor(contributor: Author?): Author? {
        contributors.add(contributor)
        return contributor
    }


    val firstTitle: String?
        /**
         * Gets the first non-blank title of the book.
         * Will return "" if no title found.
         * 
         * @return the first non-blank title of the book.
         */
        get() {
            if (titles == null || titles!!.isEmpty()) {
                return ""
            }
            for (title in titles) {
                if (!title.isNullOrBlank()) {
                    return title
                }
            }
            return ""
        }

    fun addTitle(title: String?): String? {
        this.titles!!.add(title)
        return title
    }

    fun addPublisher(publisher: String?): String? {
        this.publishers.add(publisher)
        return publisher
    }

    fun addDescription(description: String?): String? {
        this.descriptions.add(description)
        return description
    }

    @Suppress("unused")
    fun addIdentifier(identifier: Identifier?): Identifier? {
        if (this.isAutoGeneratedId && (!(identifiers.isEmpty()))) {
            identifiers.set(0, identifier)
        } else {
            identifiers.add(identifier)
        }
        this.isAutoGeneratedId = false
        return identifier
    }

    fun setIdentifiers(identifiers: MutableList<Identifier?>) {
        this.identifiers = identifiers
        this.isAutoGeneratedId = false
    }

    fun getIdentifiers(): MutableList<Identifier?> {
        return identifiers
    }

    fun addType(type: String?): String? {
        this.types.add(type)
        return type
    }

    @Suppress("unused")
    fun getMetaAttribute(name: String?): String? {
        return metaAttributes.get(name)
    }

    fun setMetaAttributes(metaAttributes: MutableMap<String?, String?>) {
        this.metaAttributes = metaAttributes
    }

    companion object {
        private val serialVersionUID = -2437262888962149444L

        const val DEFAULT_LANGUAGE: String = "en"
    }
}
