/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AudioReader: typeof import('./components/AudioReader.vue')['default']
    BookCatalogDialog: typeof import('./components/BookCatalogDialog.vue')['default']
    BookItems: typeof import('./components/BookItems.vue')['default']
    ChapterContent: typeof import('./components/ChapterContent.vue')['default']
    ComicReader: typeof import('./components/ComicReader.vue')['default']
    ReadSettings: typeof import('./components/ReadSettings.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SourceDebug: typeof import('./components/SourceDebug.vue')['default']
    SourceHelp: typeof import('./components/SourceHelp.vue')['default']
    SourceItem: typeof import('./components/SourceItem.vue')['default']
    SourceJson: typeof import('./components/SourceJson.vue')['default']
    SourceList: typeof import('./components/SourceList.vue')['default']
    SourceTabForm: typeof import('./components/SourceTabForm.vue')['default']
    SourceTabTools: typeof import('./components/SourceTabTools.vue')['default']
    TabBar: typeof import('./components/TabBar.vue')['default']
    ToolBar: typeof import('./components/ToolBar.vue')['default']
    VideoReader: typeof import('./components/VideoReader.vue')['default']
  }
}
